## ANOVA test

Here we will perform ANOVA test followed by Turkey's HSD test to see whether there is a correlation between the independent and the dependent features.

In [16]:
import pandas as pd
from scipy.stats import f_oneway
import statsmodels.stats.multicomp as mc

In [17]:
df = pd.read_csv("../dataset/merged.csv")
df.drop(columns = ["Time(ms)"], inplace = True)
df

,ankle_acc_hor_forward,ankle_acc_ver,ankle_acc_hor_lateral,upper_leg_acc_hor_forward,upper_leg_acc_ver,upper_leg_acc_hor_lateral,trunk_acc_hor_forward,trunk_acc_ver,trunk_acc_hor_lateral,annotation
0,-40,970,326,-36,962,242,320,657,349,0
1,-60,990,316,54,953,262,77,914,446,0
2,-111,980,346,-27,953,262,-48,857,446,0
3,-111,980,346,36,981,232,-38,800,446,0
4,-60,1009,346,18,972,242,77,866,436,0
...,...,...,...,...,...,...,...,...,...,...
1021876,-212,1000,376,690,-166,282,77,942,349,1
1021877,-232,970,356,572,-55,10,67,961,339,1
1021878,-232,970,356,272,92,-70,97,961,359,1
1021879,-252,921,346,354,18,-171,87,952,359,1
1021880,-232,862,366,390,111,-191,87,952,368,1

In [18]:
num_attr = df['ankle_acc_hor_forward']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 12818.10
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
     0      1 -27.8044 0.001  -28.978 -26.6308   True
     0      2 107.1434 0.001 105.0084 109.2783   True
     1      2 134.9477 0.001  132.942 136.9535   True
-----------------------------------------------------

In [19]:
num_attr = df['ankle_acc_ver']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 5321.06
p-value: 0.0000
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj  lower   upper  reject
---------------------------------------------------
     0      1  -1.9005 0.001 -2.2718 -1.5292   True
     0      2  25.9744 0.001 25.2989 26.6498   True
     1      2  27.8749 0.001 27.2403 28.5094   True
---------------------------------------------------

In [20]:
num_attr = df['ankle_acc_hor_lateral']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 387.20
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
     0      1  -2.5337 0.001  -3.1951  -1.8723   True
     0      2 -14.2573 0.001 -15.4605 -13.0542   True
     1      2 -11.7236 0.001 -12.8539 -10.5933   True
-----------------------------------------------------

In [21]:
num_attr = df['upper_leg_acc_hor_forward']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 16725.67
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
======================================================
group1 group2 meandiff p-adj   lower    upper   reject
------------------------------------------------------
     0      1 202.3513 0.001  199.7436 204.9589   True
     0      2 104.2491 0.001   99.5055 108.9927   True
     1      2 -98.1022 0.001 -102.5587 -93.6457   True
------------------------------------------------------

In [22]:
num_attr = df['upper_leg_acc_ver']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 21270.65
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
     0      1  59.9089 0.001  58.2793  61.5385   True
     0      2 260.6735 0.001 257.7091 263.6379   True
     1      2 200.7646 0.001 197.9796 203.5496   True
-----------------------------------------------------

In [23]:
num_attr = df['upper_leg_acc_hor_lateral']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 455.30
p-value: 0.0000
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj  lower   upper  reject
---------------------------------------------------
     0      1   9.0612 0.001  8.2941  9.8282   True
     0      2  12.8964 0.001 11.5011 14.2918   True
     1      2   3.8353 0.001  2.5244  5.1462   True
---------------------------------------------------

In [24]:
num_attr = df['trunk_acc_hor_forward']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 7810.88
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
     0      1  43.2715 0.001   42.411   44.132   True
     0      2   4.3558 0.001   2.7905   5.9211   True
     1      2 -38.9157 0.001 -40.3863 -37.4451   True
-----------------------------------------------------

In [25]:
num_attr = df['trunk_acc_ver']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 4737.98
p-value: 0.0000
 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj  lower    upper   reject
-----------------------------------------------------
     0      1 -14.3593 0.001 -14.7137 -14.0048   True
     0      2  -4.5125 0.001  -5.1572  -3.8677   True
     1      2   9.8468 0.001   9.2411  10.4526   True
-----------------------------------------------------

In [26]:
num_attr = df['trunk_acc_hor_lateral']
cat_attr = df['annotation']

# Group the numerical attribute by the categorical attribute
groups = [num_attr[cat_attr == category] for category in set(cat_attr)]

# Perform the ANOVA test
f_statistic, p_value = f_oneway(*groups)

# Print the results
print("F-statistic: {:.2f}".format(f_statistic))
print("p-value: {:.4f}".format(p_value))

tukey = mc.MultiComparison(num_attr, cat_attr)
tukey_result = tukey.tukeyhsd()

print(tukey_result)

F-statistic: 12467.38
p-value: 0.0000
  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
group1 group2  meandiff p-adj   lower     upper   reject
--------------------------------------------------------
     0      1  -14.3138 0.001  -15.2011  -13.4265   True
     0      2 -107.5353 0.001 -109.1495 -105.9212   True
     1      2  -93.2215 0.001   -94.738  -91.7051   True
--------------------------------------------------------

## Description of the above test

The above test was ANOVA test followed by Turkey's HSD test


ANOVA test is done to see if there is any significance difference in the means of each categories for all the attributes.

NULL Hypothesis : There is no significant difference in the means of the categories.
ALTERNATE Hypothesis : There is significant difference in the means of the categories.

Tukey's HSD (honestly significant difference) test is a post-hoc test that can be used to determine which groups are significantly different from each other after performing an ANOVA test.

Now from the above results we can conclude that for all the ANOVA tests, F-statistic value is fairly greater than the p-value and the p-value is smaller than the significance value (0.05). So we can reject the null hypothesis. Also the Turkey's HSD test has shown that the groups are significantly different from each other as the p-values of all the above HSD test table has value greater than significant value(0.05)

## Overall Conclusion regarding the Data Analysis

1. We visualized the data using the distribution plots and could not see any significant difference.
2. We plotted the correlation plot to find out multicollinearity, but could not find any multicollinearity.
3. We performed ANOVA test followed by Turkey's HSD test, and concluded that all the features are showing group wise significant difference.